# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/venus-gcam/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/venus-gcam


PRODUCT_PACKAGES += \
    GoogleCamera
