# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/googlecamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/googlecamera


PRODUCT_PACKAGES += \
    GoogleCamera
